return {
  "nvim-treesitter/nvim-treesitter",
  event = { "BufReadPre", "BufNewFile" },
  build = ":TSUpdate",
  opts = {
    ensure_installed = {
      "rust",
      "markdown",
      "markdown_inline",
      "json5",
      "javascript",
      "typescript",
      "yaml",
      "html",
      "css",
      "scss",
      "bash",
      "lua",
      "python",
      "toml",
      "regex",
      "vim",
      "vimdoc",
      "query",
      "c",
      "sql",
      "tsx",
      "c_sharp",
      "java",
      "go",
      "gomod",
      "gowork",
      "gosum",
      "http",
      "typst",
      "make",
      "nix",
      "glimmer",
      "editorconfig",
    },
    auto_install = false,
    highlight = {
      enable = true,
    },
  },
  config = function(_, opts)
    require("nvim-treesitter.configs").setup(opts)
  end,
}
