[settings]
status.missing_tools = "always"

# trusted_config_paths = ["~/code"]

# idiomatic_version_file_enable_tools = ["java", "node", "python"]
# not_found_auto_install = true

[tools]
java = "lts"
maven = "latest"
node = "lts"
